### ISSUE TITLE
MO - AT0415182 Tree Conflicts

### ISSUE THREAD

**Issue by nbyers1** [kerrymcmahon/Montgomery-County-Stormwater#13]
For the spring planting season of the AT415182 tree planting contract (begins very soon), the tree team needs to plant additional trees on existing tree assets with lower tree densities due to ROW & utility issues knocking out many of the contracted sites/acres. 3 of those tree sites have planned SWMs nearby (all at or below FI stage). We’d like to coordinate to figure out what compromises can be reached to help us meet our contract needs.

The SWM sites and their corresponding tree conflict sites are:
- MOGr2-JMT-005 is adjacent to\slightly overlaps 150002UT (mentioned in #11 )
- MOGr2-JMT-004 is adjacent to 150002UT
- MOGr2-JMT-013 overlaps 150001UT
- MO-SRF-0014 is adjacent to\slightly overlaps 150017UT
- MOGr1-RKK-432 is adjacent to 150017UT

We are asking that the SWM team review these five SWM sites and determine A) if any are unlikely to move forward and B) what the smallest buffer the SWM team can work with is for each site that will be moving forward.

![image](https://cloud.githubusercontent.com/assets/9745904/13013265/c0ace39c-d17c-11e5-9162-13aacf7c9180.png)

![image](https://cloud.githubusercontent.com/assets/9745904/13013250/b1085764-d17c-11e5-952e-3d6f5aa1c403.png)

![image](https://cloud.githubusercontent.com/assets/9745904/13013224/924d9262-d17c-11e5-9a56-e0ec8a2014c1.png)

**Comment by klangway** [comment]
Hi Natalie,
•MOGr2-JMT-005 is adjacent to\slightly overlaps 150002UT (mentioned in #11 ) : We need to **keep this for SWM** as it has potential for 0.5 - 0.8 acre credit.  We need  at least a 30' buffer, from the edge of footprint.  We can put 004 on hold and give you that area if that would work.

•MOGr2-JMT-004 is adjacent to 150002UT: We will put this site **on hold for SWM**.

•MOGr2-JMT-013 overlaps 150001UT: We need to **keep this site for SWM** as it has potential for 0.6+ acre credit.  We placed the footprint where it currently is to avoid the tree plantings up the ramp and the existing trees further down the ramp.  This is the only open area and we will need all of the space here.

•MO-SRF-0014 is adjacent to\slightly overlaps 150017UT: We will put this site **on hold for SWM**. Utilities [light pole elec] look to be in this area & minimal IAC. 

•MOGr1-RKK-432 is adjacent to 150017UT: We will put this site **on hold for SWM**.  However, please note there appears to be an existing grass swale here and along the edge of the existing tree site.  Please do not plant within the swale, so we can credit this as is.  Planting can happen outside of the swale.

Please let me know if you have any questions.
Thanks,
Kristin

**Comment by nbyers1** [comment]
Hi Kristin,

Thanks very much for commenting and for being flexible with putting some of your sites on hold! For MOGr2-JMT-005, you specified a 30' buffer. Can I assume that holds for MOGr2-JMT-013, or does that one need a 50' buffer?

Thanks,
Natalie

**Comment by klangway** [comment]
Natalie - I think generally we can go with a 30' buffer for all SWM sites, just keep in mind, some may be more, but we won't know until after concept design.  It depends on slopes & grading - the more grading we have the larger the LOD since we need to also allow for E&SC, materials, and work/equipment area.  If we find that we are having too many conflicts at final design and the 30' needs to go to 50', we can address that.

**Comment by nbyers1** [comment]
Great, thank you!

The tree team will apply a 30' buffer for MOGr2-JMT-005 and MOGr2-JMT-013 and will otherwise plant the sites as they currently exist in the database.

**Comment by klangway** [comment]
Natalie - the 30' buffer with work for 005 & most SWM sites, however as I noted in 013, this is the only open area, so I really think the existing trees on either side of our BMP footprint are within 30', so I don't see you being able to expand your tree site at this location and would appreciate being left the area for SWM.
Thanks,
Kristin

**Comment by nbyers1** [comment]
Kristin,

I'm sorry, but I don't think I understand what you're looking for for 013. Would you be available for a quick phone call to discuss? 410-462-9126

Thanks!

**Comment by nbyers1** [comment]
To follow up: During a phone call we clarified that the tree site will not be extending beyond its existing boundary and that a buffer area of 30' will be used around 013.
